# Generated by Django 4.2.28 on 2026-02-14 13:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyAggregate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("date", models.DateField(db_index=True, unique=True)),
                ("total_users", models.PositiveIntegerField(default=0)),
                ("active_users", models.PositiveIntegerField(default=0)),
                ("new_users", models.PositiveIntegerField(default=0)),
                (
                    "total_sales",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("total_orders", models.PositiveIntegerField(default=0)),
                ("licenses_activated", models.PositiveIntegerField(default=0)),
                ("licenses_expired", models.PositiveIntegerField(default=0)),
                ("total_usage_events", models.PositiveIntegerField(default=0)),
                ("abuse_attempts", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "daily aggregate",
                "verbose_name_plural": "daily aggregates",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="CohortAggregate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("cohort_date", models.DateField(db_index=True)),
                (
                    "period",
                    models.CharField(
                        choices=[("week", "Week"), ("month", "Month")], max_length=5
                    ),
                ),
                ("period_number", models.PositiveIntegerField()),
                ("user_count", models.PositiveIntegerField()),
                ("retained_count", models.PositiveIntegerField()),
                (
                    "retention_rate",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Percentage (0.00 to 100.00)",
                        max_digits=5,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "cohort aggregate",
                "verbose_name_plural": "cohort aggregates",
                "ordering": ["cohort_date", "period_number"],
                "indexes": [
                    models.Index(
                        fields=["period", "cohort_date"],
                        name="analytics_c_period_7ff040_idx",
                    )
                ],
                "unique_together": {("cohort_date", "period", "period_number")},
            },
        ),
        migrations.CreateModel(
            name="ExportJob",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "export_type",
                    models.CharField(
                        choices=[
                            ("daily_aggregates", "Daily Aggregates"),
                            ("users", "Users"),
                            ("payments", "Payments"),
                            ("licenses", "Licenses"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("parameters", models.JSONField(blank=True, default=dict)),
                ("file", models.FileField(blank=True, null=True, upload_to="exports/")),
                ("error_message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "export job",
                "verbose_name_plural": "export jobs",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status"], name="analytics_e_status_c9c0a2_idx"
                    ),
                    models.Index(
                        fields=["created_at"], name="analytics_e_created_327991_idx"
                    ),
                ],
            },
        ),
    ]
