# Generated by Django 4.2.28 on 2026-02-13 19:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DailyAggregate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("date", models.DateField(db_index=True, unique=True)),
                ("total_users", models.PositiveIntegerField(default=0)),
                ("active_users", models.PositiveIntegerField(default=0)),
                ("new_users", models.PositiveIntegerField(default=0)),
                (
                    "total_sales",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("total_orders", models.PositiveIntegerField(default=0)),
                ("licenses_activated", models.PositiveIntegerField(default=0)),
                ("licenses_expired", models.PositiveIntegerField(default=0)),
                ("total_usage_events", models.PositiveIntegerField(default=0)),
                ("abuse_attempts", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "daily aggregate",
                "verbose_name_plural": "daily aggregates",
                "ordering": ["-date"],
            },
        ),
    ]
