# Generated by Django 4.2.28 on 2026-02-14 13:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ActivationCode",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("encrypted_code", models.BinaryField(verbose_name="encrypted code")),
                (
                    "code_hash",
                    models.CharField(
                        db_index=True,
                        max_length=64,
                        unique=True,
                        verbose_name="code hash",
                    ),
                ),
                (
                    "human_code",
                    models.CharField(
                        db_index=True,
                        help_text="Formatted code for users (e.g., ABCD-EFGH-IJKL-MNOP)",
                        max_length=50,
                        verbose_name="human readable code",
                    ),
                ),
                (
                    "license_type",
                    models.CharField(
                        choices=[
                            ("TRIAL", "Trial"),
                            ("STANDARD", "Standard"),
                            ("PREMIUM", "Premium"),
                            ("ENTERPRISE", "Enterprise"),
                            ("LIFETIME", "Lifetime"),
                        ],
                        default="STANDARD",
                        max_length=20,
                        verbose_name="license type",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("GENERATED", "Generated"),
                            ("ACTIVATED", "Activated"),
                            ("REVOKED", "Revoked"),
                            ("EXPIRED", "Expired"),
                            ("SUSPENDED", "Suspended"),
                        ],
                        default="GENERATED",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "max_activations",
                    models.IntegerField(
                        default=1,
                        help_text="Maximum number of devices that can activate this code",
                        verbose_name="max activations",
                    ),
                ),
                (
                    "activation_count",
                    models.IntegerField(default=0, verbose_name="activation count"),
                ),
                (
                    "concurrent_limit",
                    models.IntegerField(
                        default=1,
                        help_text="Maximum concurrent activations",
                        verbose_name="concurrent limit",
                    ),
                ),
                (
                    "device_fingerprint",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=64,
                        null=True,
                        verbose_name="device fingerprint",
                    ),
                ),
                (
                    "device_name",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="device name"
                    ),
                ),
                (
                    "device_info",
                    models.JSONField(
                        default=dict,
                        help_text="Additional device information",
                        verbose_name="device info",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "activated_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="activated at"
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(db_index=True, verbose_name="expires at"),
                ),
                (
                    "revoked_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="revoked at"
                    ),
                ),
                (
                    "last_used_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last used at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "expiry_reminders_sent",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of reminder days already sent (e.g., [21,14,7,1,0])",
                    ),
                ),
                (
                    "last_reminder_sent_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp of the most recent reminder sent",
                        null=True,
                    ),
                ),
                (
                    "revoked_reason",
                    models.TextField(blank=True, verbose_name="revoked reason"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="notes")),
                (
                    "custom_data",
                    models.JSONField(
                        default=dict,
                        help_text="Additional custom data",
                        verbose_name="custom data",
                    ),
                ),
            ],
            options={
                "verbose_name": "activation code",
                "verbose_name_plural": "activation codes",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ActivationLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "device_fingerprint",
                    models.CharField(
                        db_index=True, max_length=64, verbose_name="device fingerprint"
                    ),
                ),
                (
                    "device_name",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="device name"
                    ),
                ),
                (
                    "device_info",
                    models.JSONField(default=dict, verbose_name="device info"),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        db_index=True, verbose_name="IP address"
                    ),
                ),
                ("user_agent", models.TextField(blank=True, verbose_name="user agent")),
                (
                    "location",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="location"
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("ACTIVATE", "Activate"),
                            ("VALIDATE", "Validate"),
                            ("DEACTIVATE", "Deactivate"),
                            ("REACTIVATE", "Reactivate"),
                            ("VERIFY", "Verify"),
                        ],
                        max_length=20,
                        verbose_name="action",
                    ),
                ),
                ("success", models.BooleanField(default=False, verbose_name="success")),
                (
                    "error_message",
                    models.TextField(blank=True, verbose_name="error message"),
                ),
                (
                    "is_suspicious",
                    models.BooleanField(default=False, verbose_name="is suspicious"),
                ),
                (
                    "suspicion_reason",
                    models.TextField(blank=True, verbose_name="suspicion reason"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
            ],
            options={
                "verbose_name": "activation log",
                "verbose_name_plural": "activation logs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CodeBatch",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="batch name")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="description"),
                ),
                (
                    "license_type",
                    models.CharField(
                        choices=[
                            ("TRIAL", "Trial"),
                            ("STANDARD", "Standard"),
                            ("PREMIUM", "Premium"),
                            ("ENTERPRISE", "Enterprise"),
                            ("LIFETIME", "Lifetime"),
                        ],
                        max_length=20,
                        verbose_name="license type",
                    ),
                ),
                ("count", models.IntegerField(verbose_name="count")),
                (
                    "max_activations",
                    models.IntegerField(default=1, verbose_name="max activations"),
                ),
                (
                    "expires_in_days",
                    models.IntegerField(default=365, verbose_name="expires in days"),
                ),
                (
                    "prefix",
                    models.CharField(
                        blank=True,
                        help_text="Prefix for generated codes",
                        max_length=10,
                        verbose_name="prefix",
                    ),
                ),
                ("is_used", models.BooleanField(default=False, verbose_name="used")),
                (
                    "used_count",
                    models.IntegerField(default=0, verbose_name="used count"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
            ],
            options={
                "verbose_name": "code batch",
                "verbose_name_plural": "code batches",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="LicenseFeature",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="name")),
                (
                    "code",
                    models.CharField(
                        db_index=True,
                        help_text="Internal code for this feature",
                        max_length=50,
                        verbose_name="feature code",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="description"),
                ),
                (
                    "available_in_trial",
                    models.BooleanField(
                        default=False, verbose_name="available in trial"
                    ),
                ),
                (
                    "available_in_standard",
                    models.BooleanField(
                        default=True, verbose_name="available in standard"
                    ),
                ),
                (
                    "available_in_premium",
                    models.BooleanField(
                        default=True, verbose_name="available in premium"
                    ),
                ),
                (
                    "available_in_enterprise",
                    models.BooleanField(
                        default=True, verbose_name="available in enterprise"
                    ),
                ),
                (
                    "requires_activation",
                    models.BooleanField(
                        default=True, verbose_name="requires activation"
                    ),
                ),
                (
                    "max_usage",
                    models.IntegerField(
                        blank=True,
                        help_text="Maximum usage count (null for unlimited)",
                        null=True,
                        verbose_name="max usage",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="active")),
                (
                    "display_order",
                    models.IntegerField(default=0, verbose_name="display order"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
            ],
            options={
                "verbose_name": "license feature",
                "verbose_name_plural": "license features",
                "ordering": ["display_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="RevocationLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("reason", models.TextField(verbose_name="reason")),
                ("details", models.JSONField(default=dict, verbose_name="details")),
                ("undone", models.BooleanField(default=False, verbose_name="undone")),
                (
                    "undone_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="undone at"
                    ),
                ),
                (
                    "undo_reason",
                    models.TextField(blank=True, verbose_name="undo reason"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "activation_code",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="revocation_logs",
                        to="licenses.activationcode",
                    ),
                ),
                (
                    "revoked_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="revocation_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "undone_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="undone_revocations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "revocation log",
                "verbose_name_plural": "revocation logs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="LicenseUsage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "usage_count",
                    models.IntegerField(default=1, verbose_name="usage count"),
                ),
                (
                    "usage_data",
                    models.JSONField(
                        default=dict,
                        help_text="Additional usage data",
                        verbose_name="usage data",
                    ),
                ),
                (
                    "device_fingerprint",
                    models.CharField(
                        db_index=True, max_length=64, verbose_name="device fingerprint"
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(verbose_name="IP address")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "activation_code",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usage_logs",
                        to="licenses.activationcode",
                    ),
                ),
                (
                    "feature",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usage_logs",
                        to="licenses.licensefeature",
                    ),
                ),
            ],
            options={
                "verbose_name": "license usage",
                "verbose_name_plural": "license usage logs",
                "ordering": ["-created_at"],
            },
        ),
    ]
