# Generated by Django 4.2.28 on 2026-02-14 13:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("licenses", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="licensefeature",
            name="software",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="license_features",
                to="products.software",
            ),
        ),
        migrations.AddField(
            model_name="codebatch",
            name="generated_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="code_batches",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="codebatch",
            name="software",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="code_batches",
                to="products.software",
            ),
        ),
        migrations.AddField(
            model_name="activationlog",
            name="activation_code",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="activation_logs",
                to="licenses.activationcode",
            ),
        ),
        migrations.AddField(
            model_name="activationcode",
            name="batch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="codes",
                to="licenses.codebatch",
                verbose_name="code batch",
            ),
        ),
        migrations.AddField(
            model_name="activationcode",
            name="generated_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="generated_codes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="activationcode",
            name="revoked_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="revoked_codes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="activationcode",
            name="software",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="activation_codes",
                to="products.software",
            ),
        ),
        migrations.AddField(
            model_name="activationcode",
            name="software_version",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="activation_codes",
                to="products.softwareversion",
            ),
        ),
        migrations.AddField(
            model_name="activationcode",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="activation_codes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="licenseusage",
            index=models.Index(
                fields=["activation_code", "feature"],
                name="licenses_li_activat_2f67a4_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="licenseusage",
            index=models.Index(
                fields=["device_fingerprint", "created_at"],
                name="licenses_li_device__172b75_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="licensefeature",
            unique_together={("software", "code")},
        ),
        migrations.AddIndex(
            model_name="activationlog",
            index=models.Index(
                fields=["activation_code", "created_at"],
                name="licenses_ac_activat_3cba4a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="activationlog",
            index=models.Index(
                fields=["device_fingerprint", "created_at"],
                name="licenses_ac_device__d81201_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="activationlog",
            index=models.Index(
                fields=["ip_address", "created_at"],
                name="licenses_ac_ip_addr_581daa_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="activationlog",
            index=models.Index(
                fields=["is_suspicious", "created_at"],
                name="licenses_ac_is_susp_6b1618_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="activationcode",
            index=models.Index(
                fields=["code_hash"], name="licenses_ac_code_ha_8b3493_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="activationcode",
            index=models.Index(
                fields=["human_code"], name="licenses_ac_human_c_8a79a3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="activationcode",
            index=models.Index(
                fields=["user", "status"], name="licenses_ac_user_id_10fd71_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="activationcode",
            index=models.Index(
                fields=["software", "status"], name="licenses_ac_softwar_c1fcd3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="activationcode",
            index=models.Index(
                fields=["expires_at", "status"], name="licenses_ac_expires_77025c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="activationcode",
            index=models.Index(
                fields=["device_fingerprint"], name="licenses_ac_device__88281e_idx"
            ),
        ),
    ]
