# Generated by Django 4.2.28 on 2026-02-13 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("licenses", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="activationcode",
            name="expiry_reminders_sent",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of reminder days already sent (e.g., [21,14,7,1,0])",
            ),
        ),
        migrations.AddField(
            model_name="activationcode",
            name="last_reminder_sent_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Timestamp of the most recent reminder sent",
                null=True,
            ),
        ),
    ]
