# Generated by Django 4.2.28 on 2026-02-14 13:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BroadcastEmail",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("subject", models.CharField(max_length=255, verbose_name="subject")),
                ("plain_body", models.TextField(verbose_name="plain text body")),
                ("html_body", models.TextField(verbose_name="HTML body")),
                (
                    "audience",
                    models.CharField(
                        choices=[
                            ("ALL", "All Users"),
                            ("ACTIVE", "Active Users (last 30 days)"),
                            ("PAID", "Paying Customers"),
                            ("ADMIN", "Administrators"),
                            ("CUSTOM", "Custom Filter (JSON)"),
                        ],
                        default="ALL",
                        max_length=20,
                        verbose_name="audience",
                    ),
                ),
                (
                    "custom_filter",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Stores Q filters as JSON (advanced).",
                        verbose_name="custom filter",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("SENDING", "Sending"),
                            ("SENT", "Sent"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="DRAFT",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "scheduled_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="scheduled at"
                    ),
                ),
                (
                    "sent_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="sent at"),
                ),
                (
                    "total_recipients",
                    models.PositiveIntegerField(
                        default=0, verbose_name="total recipients"
                    ),
                ),
                (
                    "successful_sent",
                    models.PositiveIntegerField(
                        default=0, verbose_name="successful sends"
                    ),
                ),
                (
                    "failed_sent",
                    models.PositiveIntegerField(default=0, verbose_name="failed sends"),
                ),
                (
                    "total_batches",
                    models.PositiveIntegerField(
                        default=0, verbose_name="total batches"
                    ),
                ),
                (
                    "completed_batches",
                    models.PositiveIntegerField(
                        default=0, verbose_name="completed batches"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="broadcasts_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "broadcast email",
                "verbose_name_plural": "broadcast emails",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="EmailTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.SlugField(
                        help_text="Internal identifier, e.g., 'license_expiry', 'welcome_email'",
                        unique=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="template name"),
                ),
                ("subject", models.CharField(max_length=255, verbose_name="subject")),
                ("plain_body", models.TextField(verbose_name="plain text body")),
                ("html_body", models.TextField(verbose_name="HTML body")),
                (
                    "placeholders",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of allowed placeholders (for documentation)",
                        verbose_name="placeholders",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="active")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "email template",
                "verbose_name_plural": "email templates",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("email", "Email"),
                            ("in_app", "In‑App"),
                            ("push", "Push"),
                        ],
                        max_length=10,
                    ),
                ),
                ("subject", models.CharField(blank=True, max_length=255)),
                ("body", models.TextField(blank=True)),
                ("html_body", models.TextField(blank=True)),
                ("context", models.JSONField(blank=True, default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("sent", "Sent"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True)),
                ("tracking_id", models.UUIDField(blank=True, null=True, unique=True)),
                ("opened_at", models.DateTimeField(blank=True, null=True)),
                ("clicked_at", models.DateTimeField(blank=True, null=True)),
                ("clicked_url", models.URLField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "template",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="notifications.emailtemplate",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "notification",
                "verbose_name_plural": "notifications",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="EmailTrackingEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                (
                    "event_type",
                    models.CharField(
                        choices=[("open", "Open"), ("click", "Click")], max_length=10
                    ),
                ),
                ("link_url", models.URLField(blank=True)),
                ("user_agent", models.TextField(blank=True)),
                ("ip_address", models.GenericIPAddressField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "broadcast",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tracking_events",
                        to="notifications.broadcastemail",
                    ),
                ),
                (
                    "notification",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tracking_events",
                        to="notifications.notification",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "email tracking event",
                "verbose_name_plural": "email tracking events",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="BroadcastRecipient",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "email_snapshot",
                    models.EmailField(
                        blank=True,
                        help_text="Email address of the user at the moment the broadcast was sent",
                        max_length=254,
                        null=True,
                        verbose_name="email snapshot",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("SENT", "Sent"),
                            ("FAILED", "Failed"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("error_message", models.TextField(blank=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "broadcast",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recipients",
                        to="notifications.broadcastemail",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="broadcast_recipients",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "broadcast recipient",
                "verbose_name_plural": "broadcast recipients",
            },
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["user", "created_at"], name="notificatio_user_id_c62b26_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(fields=["status"], name="notificatio_status_d92267_idx"),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["tracking_id"], name="notificatio_trackin_3bd122_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="emailtrackingevent",
            index=models.Index(
                fields=["notification"], name="notificatio_notific_badcb8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="emailtrackingevent",
            index=models.Index(
                fields=["broadcast"], name="notificatio_broadca_7596c8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="emailtrackingevent",
            index=models.Index(
                fields=["created_at"], name="notificatio_created_d2932d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="broadcastrecipient",
            index=models.Index(
                fields=["broadcast", "status"], name="notificatio_broadca_196861_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="broadcastrecipient",
            index=models.Index(fields=["user"], name="notificatio_user_id_c395cd_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="broadcastrecipient",
            unique_together={("broadcast", "user")},
        ),
    ]
