# Generated by Django 4.2.28 on 2026-02-13 10:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BroadcastEmail",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("subject", models.CharField(max_length=255, verbose_name="subject")),
                ("plain_body", models.TextField(verbose_name="plain text body")),
                ("html_body", models.TextField(verbose_name="HTML body")),
                (
                    "audience",
                    models.CharField(
                        choices=[
                            ("ALL", "All Users"),
                            ("ACTIVE", "Active Users (last 30 days)"),
                            ("PAID", "Paying Customers"),
                            ("ADMIN", "Administrators"),
                            ("CUSTOM", "Custom Filter (JSON)"),
                        ],
                        default="ALL",
                        max_length=20,
                        verbose_name="audience",
                    ),
                ),
                (
                    "custom_filter",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Stores Q filters as JSON (advanced).",
                        verbose_name="custom filter",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("SENDING", "Sending"),
                            ("SENT", "Sent"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="DRAFT",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "scheduled_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="scheduled at"
                    ),
                ),
                (
                    "sent_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="sent at"),
                ),
                (
                    "total_recipients",
                    models.PositiveIntegerField(
                        default=0, verbose_name="total recipients"
                    ),
                ),
                (
                    "successful_sent",
                    models.PositiveIntegerField(
                        default=0, verbose_name="successful sends"
                    ),
                ),
                (
                    "failed_sent",
                    models.PositiveIntegerField(default=0, verbose_name="failed sends"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="broadcasts_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "broadcast email",
                "verbose_name_plural": "broadcast emails",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="BroadcastRecipient",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("SENT", "Sent"),
                            ("FAILED", "Failed"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("error_message", models.TextField(blank=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "broadcast",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recipients",
                        to="notifications.broadcastemail",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="broadcast_recipients",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "broadcast recipient",
                "verbose_name_plural": "broadcast recipients",
                "indexes": [
                    models.Index(
                        fields=["broadcast", "status"],
                        name="notificatio_broadca_196861_idx",
                    )
                ],
                "unique_together": {("broadcast", "user")},
            },
        ),
    ]
