# Generated by Django 4.2.28 on 2026-02-13 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="broadcastemail",
            name="completed_batches",
            field=models.PositiveIntegerField(
                default=0, verbose_name="completed batches"
            ),
        ),
        migrations.AddField(
            model_name="broadcastemail",
            name="total_batches",
            field=models.PositiveIntegerField(default=0, verbose_name="total batches"),
        ),
    ]
