# Generated by Django 4.2.28 on 2026-02-13 14:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("notifications", "0002_broadcastemail_completed_batches_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.SlugField(
                        help_text="Internal identifier, e.g., 'license_expiry', 'welcome_email'",
                        unique=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="template name"),
                ),
                ("subject", models.CharField(max_length=255, verbose_name="subject")),
                ("plain_body", models.TextField(verbose_name="plain text body")),
                ("html_body", models.TextField(verbose_name="HTML body")),
                (
                    "placeholders",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of allowed placeholders (for documentation)",
                        verbose_name="placeholders",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="active")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "email template",
                "verbose_name_plural": "email templates",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="EmailTrackingEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                (
                    "event_type",
                    models.CharField(
                        choices=[("open", "Open"), ("click", "Click")], max_length=10
                    ),
                ),
                ("link_url", models.URLField(blank=True)),
                ("user_agent", models.TextField(blank=True)),
                ("ip_address", models.GenericIPAddressField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "email tracking event",
                "verbose_name_plural": "email tracking events",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("email", "Email"),
                            ("in_app", "In‑App"),
                            ("push", "Push"),
                        ],
                        max_length=10,
                    ),
                ),
                ("subject", models.CharField(blank=True, max_length=255)),
                ("body", models.TextField(blank=True)),
                ("html_body", models.TextField(blank=True)),
                ("context", models.JSONField(blank=True, default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("sent", "Sent"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True)),
                ("tracking_id", models.UUIDField(blank=True, null=True, unique=True)),
                ("opened_at", models.DateTimeField(blank=True, null=True)),
                ("clicked_at", models.DateTimeField(blank=True, null=True)),
                ("clicked_url", models.URLField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "notification",
                "verbose_name_plural": "notifications",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="broadcastrecipient",
            name="email_snapshot",
            field=models.EmailField(
                blank=True,
                help_text="Email address of the user at the moment the broadcast was sent",
                max_length=254,
                null=True,
                verbose_name="email snapshot",
            ),
        ),
        migrations.AddIndex(
            model_name="broadcastrecipient",
            index=models.Index(fields=["user"], name="notificatio_user_id_c395cd_idx"),
        ),
        migrations.AddField(
            model_name="notification",
            name="template",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="notifications.emailtemplate",
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notifications",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="emailtrackingevent",
            name="broadcast",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tracking_events",
                to="notifications.broadcastemail",
            ),
        ),
        migrations.AddField(
            model_name="emailtrackingevent",
            name="notification",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tracking_events",
                to="notifications.notification",
            ),
        ),
        migrations.AddField(
            model_name="emailtrackingevent",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["user", "created_at"], name="notificatio_user_id_c62b26_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(fields=["status"], name="notificatio_status_d92267_idx"),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["tracking_id"], name="notificatio_trackin_3bd122_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="emailtrackingevent",
            index=models.Index(
                fields=["notification"], name="notificatio_notific_badcb8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="emailtrackingevent",
            index=models.Index(
                fields=["broadcast"], name="notificatio_broadca_7596c8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="emailtrackingevent",
            index=models.Index(
                fields=["created_at"], name="notificatio_created_d2932d_idx"
            ),
        ),
    ]
