# Generated by Django 4.2.28 on 2026-02-12 18:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("licenses", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SecuritySettings",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "singleton",
                    models.BooleanField(
                        default=True,
                        editable=False,
                        help_text="Singleton flag – do not change.",
                        unique=True,
                    ),
                ),
                (
                    "activation_rate_limit",
                    models.IntegerField(
                        default=10,
                        help_text="Max activations per IP per hour",
                        verbose_name="activation rate limit",
                    ),
                ),
                (
                    "validation_rate_limit",
                    models.IntegerField(
                        default=50,
                        help_text="Max validations per IP per hour",
                        verbose_name="validation rate limit",
                    ),
                ),
                (
                    "login_rate_limit",
                    models.IntegerField(
                        default=5,
                        help_text="Max login attempts per IP per hour",
                        verbose_name="login rate limit",
                    ),
                ),
                (
                    "geo_velocity_threshold",
                    models.IntegerField(
                        default=800,
                        help_text="Maximum km/h for geographic velocity check",
                        verbose_name="geo velocity threshold",
                    ),
                ),
                (
                    "device_change_threshold",
                    models.IntegerField(
                        default=3,
                        help_text="Maximum device changes before requiring verification",
                        verbose_name="device change threshold",
                    ),
                ),
                (
                    "revocation_rate_threshold",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.3,
                        help_text="Maximum revocation rate (0-1) for automatic flagging",
                        max_digits=5,
                        verbose_name="revocation rate threshold",
                    ),
                ),
                (
                    "auto_revoke_critical",
                    models.BooleanField(
                        default=True,
                        help_text="Automatically revoke codes on critical abuse detection",
                        verbose_name="auto revoke critical",
                    ),
                ),
                (
                    "auto_block_ips",
                    models.BooleanField(
                        default=True,
                        help_text="Automatically block IPs on repeated abuse",
                        verbose_name="auto block IPs",
                    ),
                ),
                (
                    "auto_block_duration",
                    models.IntegerField(
                        default=7,
                        help_text="Duration in days for automatic IP blocks",
                        verbose_name="auto block duration",
                    ),
                ),
                (
                    "require_email_verification",
                    models.BooleanField(
                        default=True, verbose_name="require email verification"
                    ),
                ),
                (
                    "require_device_verification",
                    models.BooleanField(
                        default=True, verbose_name="require device verification"
                    ),
                ),
                (
                    "require_admin_approval",
                    models.BooleanField(
                        default=False,
                        help_text="Require admin approval for new user registrations",
                        verbose_name="require admin approval",
                    ),
                ),
                (
                    "enable_honeypots",
                    models.BooleanField(default=True, verbose_name="enable honeypots"),
                ),
                (
                    "honeypot_percentage",
                    models.IntegerField(
                        default=5,
                        help_text="Percentage of codes to convert to honeypots on abuse detection",
                        verbose_name="honeypot percentage",
                    ),
                ),
                (
                    "notify_superadmin_abuse",
                    models.BooleanField(
                        default=True, verbose_name="notify superadmin on abuse"
                    ),
                ),
                (
                    "notify_admin_abuse",
                    models.BooleanField(
                        default=True, verbose_name="notify admin on abuse"
                    ),
                ),
                (
                    "abuse_notification_threshold",
                    models.IntegerField(
                        default=7,
                        help_text="Minimum severity level to trigger notifications",
                        verbose_name="abuse notification threshold",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_security_settings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "security settings",
                "verbose_name_plural": "security settings",
            },
        ),
        migrations.CreateModel(
            name="SecurityNotificationLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "event_hash",
                    models.CharField(
                        db_index=True,
                        help_text="SHA‑256 fingerprint of the security event",
                        max_length=64,
                        unique=True,
                    ),
                ),
                ("risk_level", models.IntegerField()),
                ("ip_address", models.GenericIPAddressField()),
                ("recipient_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="security_notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Security Notification Log",
                "verbose_name_plural": "Security Notification Logs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AbuseAttempt",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        db_index=True, verbose_name="IP address"
                    ),
                ),
                (
                    "device_fingerprint",
                    models.CharField(
                        db_index=True, max_length=64, verbose_name="device fingerprint"
                    ),
                ),
                ("user_agent", models.TextField(blank=True, verbose_name="user agent")),
                (
                    "location",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="location"
                    ),
                ),
                (
                    "attempt_type",
                    models.CharField(
                        choices=[
                            ("ACTIVATION", "Activation"),
                            ("VALIDATION", "Validation"),
                            ("BRUTE_FORCE", "Brute Force"),
                            ("CODE_SHARING", "Code Sharing"),
                            ("DEVICE_MISMATCH", "Device Mismatch"),
                            ("GEO_VELOCITY", "Geographic Velocity"),
                            ("RATE_LIMIT", "Rate Limit"),
                            ("OTHER", "Other"),
                        ],
                        max_length=50,
                        verbose_name="attempt type",
                    ),
                ),
                (
                    "detection_method",
                    models.CharField(
                        choices=[
                            ("AUTO", "Automatic"),
                            ("MANUAL", "Manual"),
                            ("AI", "AI Detection"),
                            ("PATTERN", "Pattern Detection"),
                            ("HONEYPOT", "Honeypot"),
                        ],
                        default="AUTO",
                        max_length=50,
                        verbose_name="detection method",
                    ),
                ),
                (
                    "severity",
                    models.IntegerField(
                        choices=[
                            (1, "Level 1"),
                            (5, "Level 5"),
                            (8, "Level 8"),
                            (10, "Level 10"),
                        ],
                        default=5,
                        verbose_name="severity",
                    ),
                ),
                (
                    "action_taken",
                    models.CharField(
                        choices=[
                            ("NONE", "None"),
                            ("WARNED", "Warned"),
                            ("BLOCKED", "Blocked"),
                            ("REVOKED", "Revoked"),
                            ("BANNED", "Banned"),
                            ("REQUIRES_VERIFICATION", "Requires Verification"),
                        ],
                        default="NONE",
                        max_length=50,
                        verbose_name="action taken",
                    ),
                ),
                (
                    "resolved",
                    models.BooleanField(default=False, verbose_name="resolved"),
                ),
                (
                    "resolved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="resolved at"
                    ),
                ),
                (
                    "resolution_notes",
                    models.TextField(blank=True, verbose_name="resolution notes"),
                ),
                ("details", models.JSONField(default=dict, verbose_name="details")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "activation_code",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="abuse_attempts",
                        to="licenses.activationcode",
                    ),
                ),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resolved_abuses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="abuse_attempts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "abuse attempt",
                "verbose_name_plural": "abuse attempts",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AbuseAlert",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "alert_type",
                    models.CharField(
                        choices=[
                            ("CRITICAL", "Critical"),
                            ("HIGH", "High"),
                            ("MEDIUM", "Medium"),
                            ("LOW", "Low"),
                            ("INFO", "Informational"),
                        ],
                        max_length=50,
                        verbose_name="alert type",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="title")),
                ("message", models.TextField(verbose_name="message")),
                (
                    "acknowledged",
                    models.BooleanField(default=False, verbose_name="acknowledged"),
                ),
                (
                    "acknowledged_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="acknowledged at"
                    ),
                ),
                (
                    "delivered_via",
                    models.JSONField(
                        default=list,
                        help_text="Delivery methods (email, push, in-app)",
                        verbose_name="delivered via",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "abuse_attempt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alerts",
                        to="security.abuseattempt",
                    ),
                ),
                (
                    "acknowledged_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="acknowledged_alerts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "abuse alert",
                "verbose_name_plural": "abuse alerts",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="IPBlacklist",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        db_index=True, verbose_name="IP address"
                    ),
                ),
                (
                    "subnet_mask",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="CIDR notation (e.g., 24 for /24). For a single IP, use 32 (IPv4) or 128 (IPv6).",
                        null=True,
                        verbose_name="subnet mask",
                    ),
                ),
                (
                    "cidr",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        editable=False,
                        help_text="Normalized CIDR string (e.g., '192.168.1.0/24'). Auto‑generated.",
                        max_length=43,
                        verbose_name="CIDR",
                    ),
                ),
                ("reason", models.TextField(verbose_name="reason")),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("MANUAL", "Manual"),
                            ("AUTO", "Automatic"),
                            ("THREAT_INTEL", "Threat Intelligence"),
                            ("USER_REPORT", "User Report"),
                        ],
                        default="MANUAL",
                        max_length=50,
                        verbose_name="source",
                    ),
                ),
                (
                    "is_permanent",
                    models.BooleanField(default=False, verbose_name="permanent"),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Leave blank for permanent ban",
                        null=True,
                        verbose_name="expires at",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="active")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "added_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="added_blacklist_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "IP blacklist",
                "verbose_name_plural": "IP blacklist entries",
                "indexes": [
                    models.Index(
                        fields=["ip_address", "is_active"],
                        name="security_ip_ip_addr_e6acc0_idx",
                    ),
                    models.Index(
                        fields=["is_active", "expires_at"],
                        name="security_ip_is_acti_95ee68_idx",
                    ),
                    models.Index(fields=["cidr"], name="security_ip_cidr_51a734_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="HoneypotCode",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "honeypot_code",
                    models.CharField(
                        db_index=True,
                        max_length=50,
                        unique=True,
                        verbose_name="honeypot code",
                    ),
                ),
                (
                    "attacker_ip",
                    models.GenericIPAddressField(
                        db_index=True, verbose_name="attacker IP"
                    ),
                ),
                (
                    "attacker_device_fp",
                    models.CharField(
                        db_index=True,
                        max_length=64,
                        verbose_name="attacker device fingerprint",
                    ),
                ),
                (
                    "attacker_user_agent",
                    models.TextField(blank=True, verbose_name="attacker user agent"),
                ),
                (
                    "detection_method",
                    models.CharField(
                        choices=[
                            ("PATTERN", "Pattern Detection"),
                            ("BEHAVIOR", "Behavior Analysis"),
                            ("MANUAL", "Manual"),
                            ("OTHER", "Other"),
                        ],
                        default="PATTERN",
                        max_length=50,
                        verbose_name="detection method",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="active")),
                (
                    "triggered",
                    models.BooleanField(default=False, verbose_name="triggered"),
                ),
                (
                    "triggered_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="triggered at"
                    ),
                ),
                (
                    "trigger_count",
                    models.IntegerField(default=0, verbose_name="trigger count"),
                ),
                (
                    "monitor_duration",
                    models.IntegerField(
                        default=30,
                        help_text="Duration to monitor in days",
                        verbose_name="monitor duration",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "original_code",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="honeypot_codes",
                        to="licenses.activationcode",
                    ),
                ),
            ],
            options={
                "verbose_name": "honeypot code",
                "verbose_name_plural": "honeypot codes",
                "indexes": [
                    models.Index(
                        fields=["honeypot_code", "is_active"],
                        name="security_ho_honeypo_0cac8b_idx",
                    ),
                    models.Index(
                        fields=["attacker_ip", "created_at"],
                        name="security_ho_attacke_e47cba_idx",
                    ),
                    models.Index(
                        fields=["triggered", "created_at"],
                        name="security_ho_trigger_4b723a_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="CodeBlacklist",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("reason", models.TextField(verbose_name="reason")),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("MANUAL", "Manual"),
                            ("AUTO", "Automatic"),
                            ("USER_REPORT", "User Report"),
                            ("LAW_ENFORCEMENT", "Law Enforcement"),
                        ],
                        default="MANUAL",
                        max_length=50,
                        verbose_name="source",
                    ),
                ),
                (
                    "is_permanent",
                    models.BooleanField(default=True, verbose_name="permanent"),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Leave blank for permanent ban",
                        null=True,
                        verbose_name="expires at",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="active")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "activation_code",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blacklist_entry",
                        to="licenses.activationcode",
                    ),
                ),
                (
                    "added_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="added_code_blacklists",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "code blacklist",
                "verbose_name_plural": "code blacklist entries",
                "indexes": [
                    models.Index(
                        fields=["is_active", "expires_at"],
                        name="security_co_is_acti_67d8de_idx",
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="abuseattempt",
            index=models.Index(
                fields=["ip_address", "created_at"],
                name="security_ab_ip_addr_8cf8eb_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="abuseattempt",
            index=models.Index(
                fields=["device_fingerprint", "created_at"],
                name="security_ab_device__ce8dbc_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="abuseattempt",
            index=models.Index(
                fields=["user", "created_at"], name="security_ab_user_id_25e2e9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="abuseattempt",
            index=models.Index(
                fields=["activation_code", "created_at"],
                name="security_ab_activat_b5b319_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="abuseattempt",
            index=models.Index(
                fields=["severity", "resolved"], name="security_ab_severit_b97c0d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="abuseattempt",
            index=models.Index(
                fields=["attempt_type", "created_at"],
                name="security_ab_attempt_1bc7b6_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="abusealert",
            index=models.Index(
                fields=["alert_type", "created_at"],
                name="security_ab_alert_t_b7b78c_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="abusealert",
            index=models.Index(
                fields=["acknowledged", "created_at"],
                name="security_ab_acknowl_4ac51f_idx",
            ),
        ),
    ]
