# Generated by Django 4.2.28 on 2026-02-14 13:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        db_index=True,
                        max_length=254,
                        unique=True,
                        verbose_name="email address",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("USER", "User"),
                            ("ADMIN", "Admin"),
                            ("SUPER_ADMIN", "Super Admin"),
                        ],
                        db_index=True,
                        default="USER",
                        max_length=20,
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "company",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="company"
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="phone number"
                    ),
                ),
                (
                    "hardware_fingerprint",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="SHA-256 hash of device fingerprint",
                        max_length=64,
                        null=True,
                    ),
                ),
                (
                    "mfa_enabled",
                    models.BooleanField(default=False, verbose_name="MFA enabled"),
                ),
                (
                    "mfa_secret",
                    models.CharField(
                        blank=True,
                        help_text="TOTP secret key for emergency 2FA",
                        max_length=32,
                        null=True,
                    ),
                ),
                (
                    "mfa_backup_codes",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Emergency backup codes (10 total)",
                        verbose_name="MFA backup codes",
                    ),
                ),
                (
                    "mfa_emergency_only",
                    models.BooleanField(
                        default=True,
                        help_text="2FA only required for suspicious logins",
                        verbose_name="MFA emergency only",
                    ),
                ),
                (
                    "mfa_last_used",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="MFA last used"
                    ),
                ),
                (
                    "last_device_change",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last device change"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="active")),
                (
                    "is_staff",
                    models.BooleanField(default=False, verbose_name="staff status"),
                ),
                (
                    "is_verified",
                    models.BooleanField(default=False, verbose_name="verified"),
                ),
                (
                    "is_blocked",
                    models.BooleanField(default=False, verbose_name="blocked"),
                ),
                (
                    "unsubscribed",
                    models.BooleanField(
                        default=False,
                        help_text="User opted out of non‑transactional emails.",
                        verbose_name="unsubscribed from marketing",
                    ),
                ),
                (
                    "notification_preferences",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="JSON dict of notification preferences, e.g. {'email_marketing': True, 'email_expiry': False}",
                        verbose_name="notification preferences",
                    ),
                ),
                (
                    "blocked_reason",
                    models.TextField(blank=True, verbose_name="blocked reason"),
                ),
                (
                    "blocked_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="blocked at"
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "last_login_ip",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="last login IP"
                    ),
                ),
                (
                    "registration_ip",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="registration IP"
                    ),
                ),
                (
                    "blocked_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="blocked_users",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
            },
        ),
        migrations.CreateModel(
            name="AdminProfile",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="admin_profile",
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "can_manage_users",
                    models.BooleanField(default=False, verbose_name="can manage users"),
                ),
                (
                    "can_manage_licenses",
                    models.BooleanField(
                        default=True, verbose_name="can manage licenses"
                    ),
                ),
                (
                    "can_manage_payments",
                    models.BooleanField(
                        default=True, verbose_name="can manage payments"
                    ),
                ),
                (
                    "can_manage_software",
                    models.BooleanField(
                        default=True, verbose_name="can manage software"
                    ),
                ),
                (
                    "can_view_reports",
                    models.BooleanField(default=True, verbose_name="can view reports"),
                ),
                (
                    "max_users",
                    models.IntegerField(
                        default=100,
                        help_text="Maximum users this admin can manage",
                        verbose_name="max users",
                    ),
                ),
                (
                    "max_licenses",
                    models.IntegerField(
                        default=1000,
                        help_text="Maximum licenses this admin can generate",
                        verbose_name="max licenses",
                    ),
                ),
                (
                    "email_notifications",
                    models.BooleanField(
                        default=True, verbose_name="email notifications"
                    ),
                ),
                (
                    "push_notifications",
                    models.BooleanField(
                        default=True, verbose_name="push notifications"
                    ),
                ),
                (
                    "department",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="department"
                    ),
                ),
                (
                    "position",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="position"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="notes")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
            ],
            options={
                "verbose_name": "admin profile",
                "verbose_name_plural": "admin profiles",
            },
        ),
        migrations.CreateModel(
            name="DeviceChangeLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "old_fingerprint",
                    models.CharField(max_length=64, verbose_name="old fingerprint"),
                ),
                (
                    "new_fingerprint",
                    models.CharField(max_length=64, verbose_name="new fingerprint"),
                ),
                ("ip_address", models.GenericIPAddressField(verbose_name="IP address")),
                ("user_agent", models.TextField(verbose_name="user agent")),
                (
                    "verification_token",
                    models.CharField(
                        blank=True, max_length=64, verbose_name="verification token"
                    ),
                ),
                (
                    "verified",
                    models.BooleanField(default=False, verbose_name="verified"),
                ),
                (
                    "verified_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="verified at"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="device_changes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "device change log",
                "verbose_name_plural": "device change logs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UserSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "session_key",
                    models.CharField(
                        db_index=True, max_length=40, verbose_name="session key"
                    ),
                ),
                (
                    "device_fingerprint",
                    models.CharField(
                        db_index=True, max_length=64, verbose_name="device fingerprint"
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(verbose_name="IP address")),
                ("user_agent", models.TextField(blank=True, verbose_name="user agent")),
                (
                    "location",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="location"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="active")),
                (
                    "last_activity",
                    models.DateTimeField(auto_now=True, verbose_name="last activity"),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Session will be considered invalid after this time",
                        null=True,
                        verbose_name="expires at",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "user session",
                "verbose_name_plural": "user sessions",
                "indexes": [
                    models.Index(
                        fields=["user", "is_active"],
                        name="accounts_us_user_id_91ed82_idx",
                    ),
                    models.Index(
                        fields=["device_fingerprint"],
                        name="accounts_us_device__63efeb_idx",
                    ),
                    models.Index(
                        fields=["last_activity"], name="accounts_us_last_ac_a630f7_idx"
                    ),
                    models.Index(
                        fields=["expires_at"], name="accounts_us_expires_3fa67a_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="AdminActionLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("USER_CREATED", "User created"),
                            ("USER_UPDATED", "User updated"),
                            ("USER_DELETED", "User deleted"),
                            ("USER_BLOCKED", "User blocked"),
                            ("USER_UNBLOCKED", "User unblocked"),
                            ("LICENSE_GENERATED", "License generated"),
                            ("LICENSE_REVOKED", "License revoked"),
                            ("LICENSE_UPDATED", "License updated"),
                            ("PAYMENT_APPROVED", "Payment approved"),
                            ("PAYMENT_REJECTED", "Payment rejected"),
                            ("SOFTWARE_ADDED", "Software added"),
                            ("SOFTWARE_UPDATED", "Software updated"),
                            ("SOFTWARE_DELETED", "Software deleted"),
                            ("SETTINGS_UPDATED", "Settings updated"),
                            ("ACTION_UNDONE", "Action undone"),
                            ("MFA_USAGE", "MFA usage"),
                        ],
                        max_length=50,
                        verbose_name="action type",
                    ),
                ),
                (
                    "target_id",
                    models.UUIDField(blank=True, null=True, verbose_name="target ID"),
                ),
                (
                    "target_type",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="target type"
                    ),
                ),
                ("details", models.JSONField(default=dict, verbose_name="details")),
                ("ip_address", models.GenericIPAddressField(verbose_name="IP address")),
                ("user_agent", models.TextField(blank=True, verbose_name="user agent")),
                (
                    "reversed",
                    models.BooleanField(default=False, verbose_name="reversed"),
                ),
                (
                    "undo_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="undo at"),
                ),
                (
                    "undo_reason",
                    models.TextField(blank=True, verbose_name="undo reason"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "undo_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="undone_actions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="actions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "admin action log",
                "verbose_name_plural": "admin action logs",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "created_at"],
                        name="accounts_ad_user_id_736055_idx",
                    ),
                    models.Index(
                        fields=["action_type", "created_at"],
                        name="accounts_ad_action__44b015_idx",
                    ),
                    models.Index(
                        fields=["target_id", "target_type"],
                        name="accounts_ad_target__4f534e_idx",
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["email"], name="accounts_us_email_74c8d6_idx"),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["role", "is_active"], name="accounts_us_role_2b136f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["date_joined"], name="accounts_us_date_jo_ff39bb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["last_login"], name="accounts_us_last_lo_42da58_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["is_active"], name="accounts_us_is_acti_a5841d_idx"
            ),
        ),
    ]
