# Generated by Django 4.2.28 on 2026-02-16 14:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('LOGIN_FAILED', 'Login Failed'), ('SUSPICIOUS_LOGIN_DETECTED', 'Suspicious Login Detected'), ('PASSWORD_CHANGED', 'Password Changed'), ('PASSWORD_RESET', 'Password Reset'), ('2FA_FAILED', '2FA Failed'), ('2FA_VERIFIED', '2FA Verified'), ('DEVICE_VERIFIED', 'Device Verified'), ('UNSUBSCRIBED', 'Unsubscribed'), ('NOTIFICATION_PREFERENCES_UPDATED', 'Notification Preferences Updated')], db_index=True, help_text='Type of security event.', max_length=50)),
                ('target', models.CharField(blank=True, help_text="String representation of the target (e.g., 'user:123', 'device:abc').", max_length=255)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address from which the event originated.', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='User agent string of the client.')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional structured data about the event (passwords redacted).')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when the event occurred.')),
                ('actor', models.ForeignKey(blank=True, help_text='User who performed the action (may be None for anonymous events).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='security_logs_as_actor', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'security log',
                'verbose_name_plural': 'security logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['created_at'], name='accounts_se_created_93f558_idx'), models.Index(fields=['action', 'created_at'], name='accounts_se_action_505bcb_idx')],
            },
        ),
    ]
