# Generated by Django 4.2.28 on 2026-02-11 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="mfa_backup_codes",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Emergency backup codes (10 total)",
                verbose_name="MFA backup codes",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="mfa_emergency_only",
            field=models.BooleanField(
                default=True,
                help_text="2FA only required for suspicious logins",
                verbose_name="MFA emergency only",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="mfa_last_used",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="MFA last used"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="mfa_secret",
            field=models.CharField(
                blank=True,
                help_text="TOTP secret key for emergency 2FA",
                max_length=32,
                null=True,
            ),
        ),
    ]
