# Generated by Django 4.2.28 on 2026-02-13 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_user_mfa_backup_codes_user_mfa_emergency_only_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="adminprofile",
            name="can_impersonate",
        ),
        migrations.AddField(
            model_name="user",
            name="unsubscribed",
            field=models.BooleanField(
                default=False,
                help_text="User opted out of non‑transactional emails.",
                verbose_name="unsubscribed from marketing",
            ),
        ),
        migrations.AddField(
            model_name="usersession",
            name="expires_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Session will be considered invalid after this time",
                null=True,
                verbose_name="expires at",
            ),
        ),
        migrations.AlterField(
            model_name="adminactionlog",
            name="action_type",
            field=models.CharField(
                choices=[
                    ("USER_CREATED", "User created"),
                    ("USER_UPDATED", "User updated"),
                    ("USER_DELETED", "User deleted"),
                    ("USER_BLOCKED", "User blocked"),
                    ("USER_UNBLOCKED", "User unblocked"),
                    ("LICENSE_GENERATED", "License generated"),
                    ("LICENSE_REVOKED", "License revoked"),
                    ("LICENSE_UPDATED", "License updated"),
                    ("PAYMENT_APPROVED", "Payment approved"),
                    ("PAYMENT_REJECTED", "Payment rejected"),
                    ("SOFTWARE_ADDED", "Software added"),
                    ("SOFTWARE_UPDATED", "Software updated"),
                    ("SOFTWARE_DELETED", "Software deleted"),
                    ("SETTINGS_UPDATED", "Settings updated"),
                    ("ACTION_UNDONE", "Action undone"),
                    ("MFA_USAGE", "MFA usage"),
                ],
                max_length=50,
                verbose_name="action type",
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["last_login"], name="accounts_us_last_lo_42da58_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["is_active"], name="accounts_us_is_acti_a5841d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="usersession",
            index=models.Index(
                fields=["expires_at"], name="accounts_us_expires_3fa67a_idx"
            ),
        ),
    ]
