# Generated by Django 4.2.28 on 2026-02-13 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_remove_adminprofile_can_impersonate_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="notification_preferences",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="JSON dict of notification preferences, e.g. {'email_marketing': True, 'email_expiry': False}",
                verbose_name="notification preferences",
            ),
        ),
    ]
