# Generated by Django 4.2.28 on 2026-02-14 13:20

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("licenses", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Coupon",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True, max_length=50, unique=True, verbose_name="code"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="description"),
                ),
                (
                    "discount_type",
                    models.CharField(
                        choices=[
                            ("PERCENTAGE", "Percentage"),
                            ("FIXED", "Fixed Amount"),
                        ],
                        default="PERCENTAGE",
                        max_length=10,
                        verbose_name="discount type",
                    ),
                ),
                (
                    "discount_value",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="discount value"
                    ),
                ),
                (
                    "max_discount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Maximum discount amount (for percentage discounts)",
                        max_digits=10,
                        null=True,
                        verbose_name="max discount",
                    ),
                ),
                ("valid_from", models.DateTimeField(verbose_name="valid from")),
                ("valid_until", models.DateTimeField(verbose_name="valid until")),
                (
                    "max_uses",
                    models.IntegerField(
                        blank=True,
                        help_text="Maximum number of times this coupon can be used",
                        null=True,
                        verbose_name="max uses",
                    ),
                ),
                (
                    "max_uses_per_user",
                    models.IntegerField(
                        default=1,
                        help_text="Maximum number of times a single user can use this coupon",
                        verbose_name="max uses per user",
                    ),
                ),
                (
                    "minimum_purchase",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Minimum purchase amount required",
                        max_digits=10,
                        verbose_name="minimum purchase",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="active")),
                (
                    "times_used",
                    models.IntegerField(default=0, verbose_name="times used"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "applicable_software",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Leave empty to apply to all software",
                        related_name="coupons",
                        to="products.software",
                    ),
                ),
            ],
            options={
                "verbose_name": "coupon",
                "verbose_name_plural": "coupons",
            },
        ),
        migrations.CreateModel(
            name="Plan",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("code", models.SlugField(unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                ("currency", models.CharField(default="USD", max_length=3)),
                (
                    "interval",
                    models.CharField(
                        choices=[
                            ("month", "Monthly"),
                            ("year", "Yearly"),
                            ("lifetime", "Lifetime"),
                        ],
                        max_length=10,
                    ),
                ),
                ("trial_days", models.PositiveIntegerField(default=0)),
                ("features", models.JSONField(blank=True, default=dict)),
                ("is_active", models.BooleanField(default=True)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "plan",
                "verbose_name_plural": "plans",
                "ordering": ["sort_order", "price"],
            },
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="amount"
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="USD", max_length=3, verbose_name="currency"
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("STRIPE", "Stripe"),
                            ("PAYPAL", "PayPal"),
                            ("PAYSTACK", "Paystack"),
                            ("BANK_TRANSFER", "Bank Transfer"),
                            ("BANK_DEPOSIT", "Bank Deposit"),
                            ("BITCOIN", "Bitcoin"),
                            ("CRYPTO", "Cryptocurrency"),
                            ("OTHER", "Other"),
                        ],
                        max_length=20,
                        verbose_name="payment method",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("PROCESSING", "Processing"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                            ("REFUNDED", "Refunded"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="PENDING",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "status_reason",
                    models.TextField(blank=True, verbose_name="status reason"),
                ),
                (
                    "transaction_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=255,
                        null=True,
                        unique=True,
                        verbose_name="transaction ID",
                    ),
                ),
                (
                    "gateway_reference",
                    models.CharField(
                        blank=True,
                        help_text="Reference ID from payment gateway",
                        max_length=255,
                        verbose_name="gateway reference",
                    ),
                ),
                ("metadata", models.JSONField(default=dict, verbose_name="metadata")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="completed at"
                    ),
                ),
                (
                    "refunded_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="refunded at"
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp after which this payment is considered expired.",
                        null=True,
                        verbose_name="expires at",
                    ),
                ),
                (
                    "software",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="products.software",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "payment",
                "verbose_name_plural": "payments",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OfflinePayment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "receipt_file",
                    models.FileField(
                        blank=True,
                        max_length=500,
                        null=True,
                        upload_to="receipts/%Y/%m/%d/",
                        verbose_name="receipt file",
                    ),
                ),
                (
                    "receipt_text",
                    models.TextField(blank=True, verbose_name="receipt text"),
                ),
                (
                    "receipt_verified",
                    models.BooleanField(default=False, verbose_name="receipt verified"),
                ),
                (
                    "bank_name",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="bank name"
                    ),
                ),
                (
                    "account_name",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="account name"
                    ),
                ),
                (
                    "account_number",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="account number"
                    ),
                ),
                (
                    "routing_number",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="routing number"
                    ),
                ),
                (
                    "reference_number",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="reference number"
                    ),
                ),
                (
                    "crypto_address",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="crypto address"
                    ),
                ),
                (
                    "crypto_tx_hash",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        verbose_name="crypto transaction hash",
                    ),
                ),
                (
                    "crypto_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=8,
                        max_digits=20,
                        null=True,
                        verbose_name="crypto amount",
                    ),
                ),
                (
                    "crypto_currency",
                    models.CharField(
                        blank=True, max_length=10, verbose_name="crypto currency"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("UNDER_REVIEW", "Under Review"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="PENDING",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "reviewed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="reviewed at"
                    ),
                ),
                (
                    "review_notes",
                    models.TextField(blank=True, verbose_name="review notes"),
                ),
                (
                    "appeal_requested",
                    models.BooleanField(default=False, verbose_name="appeal requested"),
                ),
                (
                    "appeal_reason",
                    models.TextField(blank=True, verbose_name="appeal reason"),
                ),
                (
                    "appeal_reviewed",
                    models.BooleanField(default=False, verbose_name="appeal reviewed"),
                ),
                (
                    "appeal_reviewed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="appeal reviewed at"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "appeal_reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_appeals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "payment",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="offline_payment",
                        to="payments.payment",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_payments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "offline payment",
                "verbose_name_plural": "offline payments",
            },
        ),
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "invoice_number",
                    models.CharField(
                        db_index=True,
                        max_length=50,
                        unique=True,
                        verbose_name="invoice number",
                    ),
                ),
                (
                    "billing_name",
                    models.CharField(max_length=255, verbose_name="billing name"),
                ),
                (
                    "billing_email",
                    models.EmailField(max_length=254, verbose_name="billing email"),
                ),
                (
                    "billing_phone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="billing phone"
                    ),
                ),
                (
                    "billing_address",
                    models.TextField(blank=True, verbose_name="billing address"),
                ),
                (
                    "billing_city",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="billing city"
                    ),
                ),
                (
                    "billing_state",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="billing state"
                    ),
                ),
                (
                    "billing_country",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="billing country"
                    ),
                ),
                (
                    "billing_zip",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="billing zip"
                    ),
                ),
                (
                    "tax_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="tax amount",
                    ),
                ),
                (
                    "tax_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="tax rate",
                    ),
                ),
                (
                    "tax_id",
                    models.CharField(blank=True, max_length=50, verbose_name="tax ID"),
                ),
                (
                    "subtotal",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="subtotal"
                    ),
                ),
                (
                    "discount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="discount",
                    ),
                ),
                (
                    "total",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="total"
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="USD", max_length=3, verbose_name="currency"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("issued", "Issued"),
                            ("paid", "Paid"),
                            ("void", "Void"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                ("issued_at", models.DateTimeField(blank=True, null=True)),
                ("is_paid", models.BooleanField(default=False, verbose_name="paid")),
                (
                    "paid_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="paid at"),
                ),
                (
                    "pdf_file",
                    models.FileField(
                        blank=True,
                        max_length=500,
                        null=True,
                        upload_to="invoices/%Y/%m/%d/",
                        verbose_name="PDF file",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="notes")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "payment",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invoice",
                        to="payments.payment",
                    ),
                ),
            ],
            options={
                "verbose_name": "invoice",
                "verbose_name_plural": "invoices",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="GatewayEventLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("gateway", models.CharField(db_index=True, max_length=20)),
                (
                    "event_type",
                    models.CharField(
                        blank=True, db_index=True, max_length=50, null=True
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        blank=True, db_index=True, max_length=255, null=True
                    ),
                ),
                ("payload", models.JSONField()),
                ("raw_payload", models.TextField(blank=True)),
                ("status_code", models.PositiveSmallIntegerField(default=200)),
                ("error_message", models.TextField(blank=True)),
                (
                    "correlation_id",
                    models.CharField(blank=True, db_index=True, max_length=64),
                ),
                (
                    "payload_hash",
                    models.CharField(
                        blank=True, editable=False, max_length=64, unique=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "gateway event log",
                "verbose_name_plural": "gateway event logs",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["gateway", "-created_at"],
                        name="payments_ga_gateway_fe3bf6_idx",
                    ),
                    models.Index(
                        fields=["reference", "gateway"],
                        name="payments_ga_referen_4e9ace_idx",
                    ),
                    models.Index(
                        fields=["correlation_id"], name="payments_ga_correla_ed18ec_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="CouponUsage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "coupon",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usages",
                        to="payments.coupon",
                    ),
                ),
                (
                    "payment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="coupon_usages",
                        to="payments.payment",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="coupon_usages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "coupon usage",
                "verbose_name_plural": "coupon usages",
            },
        ),
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "plan_name",
                    models.CharField(max_length=100, verbose_name="plan name"),
                ),
                (
                    "billing_cycle",
                    models.CharField(
                        choices=[
                            ("MONTHLY", "Monthly"),
                            ("QUARTERLY", "Quarterly"),
                            ("YEARLY", "Yearly"),
                            ("LIFETIME", "Lifetime"),
                        ],
                        max_length=20,
                        verbose_name="billing cycle",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="amount"
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="USD", max_length=3, verbose_name="currency"
                    ),
                ),
                (
                    "setup_fee",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="setup fee",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("CANCELLED", "Cancelled"),
                            ("EXPIRED", "Expired"),
                            ("SUSPENDED", "Suspended"),
                            ("PENDING", "Pending"),
                        ],
                        default="PENDING",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                ("start_date", models.DateTimeField(verbose_name="start date")),
                ("end_date", models.DateTimeField(verbose_name="end date")),
                (
                    "next_billing_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="next billing date"
                    ),
                ),
                (
                    "cancelled_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="cancelled at"
                    ),
                ),
                ("current_period_start", models.DateTimeField(blank=True, null=True)),
                ("current_period_end", models.DateTimeField(blank=True, null=True)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                (
                    "grace_period_until",
                    models.DateTimeField(
                        blank=True,
                        help_text="If set, access remains valid until this date even after expiry.",
                        null=True,
                        verbose_name="grace period until",
                    ),
                ),
                (
                    "auto_renew",
                    models.BooleanField(default=True, verbose_name="auto renew"),
                ),
                (
                    "renewal_failed",
                    models.BooleanField(default=False, verbose_name="renewal failed"),
                ),
                (
                    "renewal_failure_reason",
                    models.TextField(blank=True, verbose_name="renewal failure reason"),
                ),
                ("cancel_at_period_end", models.BooleanField(default=False)),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("STRIPE", "Stripe"),
                            ("PAYPAL", "PayPal"),
                            ("PAYSTACK", "Paystack"),
                            ("BANK_TRANSFER", "Bank Transfer"),
                            ("BANK_DEPOSIT", "Bank Deposit"),
                            ("BITCOIN", "Bitcoin"),
                            ("CRYPTO", "Cryptocurrency"),
                            ("OTHER", "Other"),
                        ],
                        max_length=20,
                        verbose_name="payment method",
                    ),
                ),
                (
                    "payment_gateway_id",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="payment gateway ID"
                    ),
                ),
                ("metadata", models.JSONField(default=dict, verbose_name="metadata")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "activation_code",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="subscription",
                        to="licenses.activationcode",
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="subscriptions",
                        to="payments.plan",
                    ),
                ),
                (
                    "software",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscriptions",
                        to="products.software",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscriptions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "subscription",
                "verbose_name_plural": "subscriptions",
                "indexes": [
                    models.Index(
                        fields=["user", "status"], name="payments_su_user_id_058311_idx"
                    ),
                    models.Index(
                        fields=["software", "status"],
                        name="payments_su_softwar_029cd3_idx",
                    ),
                    models.Index(
                        fields=["status", "end_date"],
                        name="payments_su_status_79c6da_idx",
                    ),
                    models.Index(
                        fields=["next_billing_date"],
                        name="payments_su_next_bi_574c1e_idx",
                    ),
                    models.Index(
                        fields=["current_period_end"],
                        name="payments_su_current_d26b0c_idx",
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="subscription",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "ACTIVE")),
                fields=("user",),
                name="unique_active_subscription_per_user",
            ),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["user", "status"], name="payments_pa_user_id_01767a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["transaction_id"], name="payments_pa_transac_8e9d99_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["created_at"], name="payments_pa_created_b8a300_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["status", "created_at"], name="payments_pa_status_343680_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["expires_at"], name="payments_pa_expires_32b381_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="offlinepayment",
            index=models.Index(
                fields=["status", "created_at"], name="payments_of_status_5253a3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="offlinepayment",
            index=models.Index(
                fields=["payment", "status"], name="payments_of_payment_33f04c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(fields=["status"], name="payments_in_status_45b876_idx"),
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(
                fields=["issued_at"], name="payments_in_issued__210b19_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="couponusage",
            index=models.Index(
                fields=["coupon", "user"], name="payments_co_coupon__af7ed8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="couponusage",
            index=models.Index(
                fields=["coupon", "created_at"], name="payments_co_coupon__35acc7_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="couponusage",
            constraint=models.UniqueConstraint(
                fields=("coupon", "user", "payment"), name="unique_coupon_user_payment"
            ),
        ),
        migrations.AddConstraint(
            model_name="couponusage",
            constraint=models.UniqueConstraint(
                condition=models.Q(("payment__isnull", True)),
                fields=("coupon", "user"),
                name="unique_coupon_user_no_payment",
            ),
        ),
        migrations.AddIndex(
            model_name="coupon",
            index=models.Index(
                fields=["code", "is_active"], name="payments_co_code_ea251b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="coupon",
            index=models.Index(
                fields=["valid_from", "valid_until"],
                name="payments_co_valid_f_ca0eaf_idx",
            ),
        ),
    ]
