# Generated by Django 4.2.28 on 2026-02-14 13:20

import backend.apps.products.models
from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("licenses", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, unique=True, verbose_name="name"),
                ),
                (
                    "slug",
                    models.SlugField(max_length=100, unique=True, verbose_name="slug"),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="description"),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        help_text="FontAwesome icon class",
                        max_length=50,
                        verbose_name="icon",
                    ),
                ),
                (
                    "display_order",
                    models.IntegerField(default=0, verbose_name="display order"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="active")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="subcategories",
                        to="products.category",
                    ),
                ),
            ],
            options={
                "verbose_name": "category",
                "verbose_name_plural": "categories",
                "ordering": ["display_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Software",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="name")),
                (
                    "slug",
                    models.SlugField(max_length=255, unique=True, verbose_name="slug"),
                ),
                (
                    "app_code",
                    models.CharField(
                        help_text="Unique code for this software (e.g., 'WINAPP001')",
                        max_length=10,
                        unique=True,
                        verbose_name="application code",
                    ),
                ),
                (
                    "tags",
                    models.JSONField(
                        default=list,
                        help_text="List of tags for filtering",
                        verbose_name="tags",
                    ),
                ),
                (
                    "short_description",
                    models.TextField(blank=True, verbose_name="short description"),
                ),
                (
                    "full_description",
                    models.TextField(blank=True, verbose_name="full description"),
                ),
                (
                    "features",
                    models.JSONField(
                        default=list,
                        help_text="List of features",
                        verbose_name="features",
                    ),
                ),
                (
                    "requirements",
                    models.JSONField(
                        default=list,
                        help_text="System requirements",
                        verbose_name="requirements",
                    ),
                ),
                (
                    "base_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=10,
                        verbose_name="base price",
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="USD", max_length=3, verbose_name="currency"
                    ),
                ),
                (
                    "license_type",
                    models.CharField(
                        choices=[
                            ("PERPETUAL", "Perpetual"),
                            ("SUBSCRIPTION", "Subscription"),
                            ("TRIAL", "Trial"),
                            ("FLOATING", "Floating"),
                            ("CONCURRENT", "Concurrent"),
                        ],
                        default="PERPETUAL",
                        max_length=20,
                        verbose_name="license type",
                    ),
                ),
                (
                    "has_trial",
                    models.BooleanField(default=False, verbose_name="has trial"),
                ),
                (
                    "trial_days",
                    models.IntegerField(default=14, verbose_name="trial days"),
                ),
                (
                    "trial_features",
                    models.JSONField(
                        default=list,
                        help_text="Features available in trial version",
                        verbose_name="trial features",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="active")),
                (
                    "is_featured",
                    models.BooleanField(default=False, verbose_name="featured"),
                ),
                ("is_new", models.BooleanField(default=False, verbose_name="new")),
                (
                    "display_order",
                    models.IntegerField(default=0, verbose_name="display order"),
                ),
                (
                    "download_count",
                    models.IntegerField(default=0, verbose_name="download count"),
                ),
                (
                    "average_rating",
                    models.FloatField(default=0.0, verbose_name="average rating"),
                ),
                (
                    "review_count",
                    models.IntegerField(default=0, verbose_name="review count"),
                ),
                (
                    "released_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="released at"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="software",
                        to="products.category",
                    ),
                ),
            ],
            options={
                "verbose_name": "software",
                "verbose_name_plural": "software",
                "ordering": ["display_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="SoftwareImage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "image_type",
                    models.CharField(
                        choices=[
                            ("LOGO", "Logo"),
                            ("SCREENSHOT", "Screenshot"),
                            ("BANNER", "Banner"),
                            ("ICON", "Icon"),
                            ("OTHER", "Other"),
                        ],
                        max_length=20,
                        verbose_name="image type",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        max_length=500,
                        upload_to="software_images/%Y/%m/%d/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=[
                                    "jpg",
                                    "jpeg",
                                    "png",
                                    "gif",
                                    "svg",
                                    "webp",
                                ]
                            )
                        ],
                        verbose_name="image",
                    ),
                ),
                (
                    "alt_text",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="alt text"
                    ),
                ),
                (
                    "caption",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="caption"
                    ),
                ),
                (
                    "display_order",
                    models.IntegerField(default=0, verbose_name="display order"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="active")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "software",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="products.software",
                    ),
                ),
            ],
            options={
                "verbose_name": "software image",
                "verbose_name_plural": "software images",
                "ordering": ["display_order"],
            },
        ),
        migrations.CreateModel(
            name="SoftwareDocument",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("MANUAL", "User Manual"),
                            ("GUIDE", "Installation Guide"),
                            ("API", "API Documentation"),
                            ("LICENSE", "License Agreement"),
                            ("RELEASE_NOTES", "Release Notes"),
                            ("OTHER", "Other"),
                        ],
                        max_length=20,
                        verbose_name="document type",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="title")),
                (
                    "file",
                    models.FileField(
                        max_length=500,
                        upload_to="software_docs/%Y/%m/%d/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=[
                                    "pdf",
                                    "doc",
                                    "docx",
                                    "txt",
                                    "md",
                                    "rtf",
                                ]
                            )
                        ],
                        verbose_name="file",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="description"),
                ),
                (
                    "language",
                    models.CharField(
                        default="en", max_length=10, verbose_name="language"
                    ),
                ),
                (
                    "version",
                    models.CharField(blank=True, max_length=50, verbose_name="version"),
                ),
                (
                    "download_count",
                    models.IntegerField(default=0, verbose_name="download count"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="active")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "software",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="products.software",
                    ),
                ),
            ],
            options={
                "verbose_name": "software document",
                "verbose_name_plural": "software documents",
            },
        ),
        migrations.CreateModel(
            name="SoftwareVersion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "version_number",
                    models.CharField(max_length=50, verbose_name="version number"),
                ),
                (
                    "version_code",
                    models.CharField(
                        help_text="Internal version code (e.g., '1.0.0.1234')",
                        max_length=20,
                        verbose_name="version code",
                    ),
                ),
                (
                    "version_major",
                    models.IntegerField(
                        blank=True,
                        editable=False,
                        help_text="Auto‑populated from version_number",
                        null=True,
                        verbose_name="major version",
                    ),
                ),
                (
                    "version_minor",
                    models.IntegerField(
                        blank=True,
                        editable=False,
                        null=True,
                        verbose_name="minor version",
                    ),
                ),
                (
                    "version_patch",
                    models.IntegerField(
                        blank=True,
                        editable=False,
                        null=True,
                        verbose_name="patch version",
                    ),
                ),
                (
                    "version_prerelease",
                    models.CharField(
                        blank=True,
                        editable=False,
                        max_length=50,
                        verbose_name="prerelease tag",
                    ),
                ),
                (
                    "release_name",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="release name"
                    ),
                ),
                (
                    "release_notes",
                    models.TextField(blank=True, verbose_name="release notes"),
                ),
                ("changelog", models.TextField(blank=True, verbose_name="changelog")),
                (
                    "binary_file",
                    models.FileField(
                        max_length=500,
                        upload_to="software/%Y/%m/%d/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=[
                                    "exe",
                                    "msi",
                                    "dmg",
                                    "deb",
                                    "rpm",
                                    "zip",
                                    "tar.gz",
                                    "appimage",
                                ]
                            ),
                            backend.apps.products.models.SoftwareVersion.validate_file_size,
                        ],
                        verbose_name="binary file",
                    ),
                ),
                (
                    "binary_size",
                    models.BigIntegerField(
                        default=0, editable=False, verbose_name="binary size"
                    ),
                ),
                (
                    "binary_checksum",
                    models.CharField(
                        blank=True,
                        editable=False,
                        help_text="SHA-256 checksum of the binary",
                        max_length=64,
                        verbose_name="binary checksum",
                    ),
                ),
                (
                    "installer_file",
                    models.FileField(
                        blank=True,
                        max_length=500,
                        null=True,
                        upload_to="installers/%Y/%m/%d/",
                        validators=[
                            backend.apps.products.models.SoftwareVersion.validate_file_size
                        ],
                        verbose_name="installer file",
                    ),
                ),
                (
                    "supported_os",
                    models.JSONField(
                        default=list,
                        help_text="List of supported operating systems",
                        verbose_name="supported OS",
                    ),
                ),
                (
                    "min_requirements",
                    models.JSONField(
                        default=dict,
                        help_text="Minimum system requirements",
                        verbose_name="minimum requirements",
                    ),
                ),
                (
                    "recommended_requirements",
                    models.JSONField(
                        default=dict,
                        help_text="Recommended system requirements",
                        verbose_name="recommended requirements",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="active")),
                ("is_beta", models.BooleanField(default=False, verbose_name="beta")),
                ("is_stable", models.BooleanField(default=True, verbose_name="stable")),
                (
                    "is_signed",
                    models.BooleanField(default=False, verbose_name="signed"),
                ),
                (
                    "signature_file",
                    models.FileField(
                        blank=True,
                        max_length=500,
                        null=True,
                        upload_to="signatures/%Y/%m/%d/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["sig", "asc", "sign"]
                            )
                        ],
                        verbose_name="signature file",
                    ),
                ),
                (
                    "download_count",
                    models.IntegerField(default=0, verbose_name="download count"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "released_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="released at"
                    ),
                ),
                (
                    "software",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="products.software",
                    ),
                ),
            ],
            options={
                "verbose_name": "software version",
                "verbose_name_plural": "software versions",
                "ordering": [
                    "software",
                    "-version_major",
                    "-version_minor",
                    "-version_patch",
                    "-version_prerelease",
                ],
                "indexes": [
                    models.Index(
                        fields=["software", "is_active"],
                        name="products_so_softwar_59b8ee_idx",
                    ),
                    models.Index(
                        fields=["is_active", "is_stable"],
                        name="products_so_is_acti_316217_idx",
                    ),
                    models.Index(
                        fields=["released_at"], name="products_so_release_23d509_idx"
                    ),
                    models.Index(
                        fields=["-download_count"], name="version_download_idx"
                    ),
                    models.Index(
                        fields=["version_major", "version_minor", "version_patch"],
                        name="version_semver_idx",
                    ),
                    models.Index(
                        fields=["binary_checksum"], name="version_checksum_idx"
                    ),
                ],
                "unique_together": {("software", "version_number")},
            },
        ),
        migrations.CreateModel(
            name="SoftwareUsageEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("launch", "Launch"),
                            ("feature_x_used", "Feature X Used"),
                        ],
                        help_text="Type of usage event",
                        max_length=50,
                    ),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "activation_code",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="usage_events",
                        to="licenses.activationcode",
                    ),
                ),
                (
                    "software",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usage_events",
                        to="products.software",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="software_usage_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "software usage event",
                "verbose_name_plural": "software usage events",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["software", "created_at"],
                        name="products_so_softwar_d87d75_idx",
                    ),
                    models.Index(
                        fields=["user", "created_at"],
                        name="products_so_user_id_88ff7a_idx",
                    ),
                    models.Index(
                        fields=["event_type"], name="products_so_event_t_ccfa2b_idx"
                    ),
                    models.Index(
                        fields=["software", "event_type", "created_at"],
                        name="products_so_softwar_155d69_idx",
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="softwareimage",
            constraint=models.UniqueConstraint(
                condition=models.Q(("image_type", "LOGO")),
                fields=("software", "image_type"),
                name="unique_logo_per_software",
            ),
        ),
        migrations.AddConstraint(
            model_name="softwaredocument",
            constraint=models.UniqueConstraint(
                fields=("software", "document_type", "version", "language"),
                name="unique_document_per_software_type_version_lang",
            ),
        ),
        migrations.AddIndex(
            model_name="software",
            index=models.Index(fields=["slug"], name="products_so_slug_b99d9f_idx"),
        ),
        migrations.AddIndex(
            model_name="software",
            index=models.Index(
                fields=["app_code"], name="products_so_app_cod_a144a2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="software",
            index=models.Index(
                fields=["is_active", "is_featured"],
                name="products_so_is_acti_7d3b7d_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="software",
            index=models.Index(
                fields=["category", "is_active"], name="products_so_categor_01708b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="software",
            index=models.Index(
                fields=["-download_count"], name="software_download_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="software",
            index=models.Index(fields=["-released_at"], name="software_release_idx"),
        ),
        migrations.AddIndex(
            model_name="software",
            index=models.Index(fields=["license_type"], name="software_license_idx"),
        ),
        migrations.AddIndex(
            model_name="software",
            index=models.Index(fields=["base_price"], name="software_price_idx"),
        ),
    ]
