# Generated by Django 4.2.28 on 2026-02-12 18:47

import backend.apps.products.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="softwareversion",
            options={
                "ordering": [
                    "software",
                    "-version_major",
                    "-version_minor",
                    "-version_patch",
                    "-version_prerelease",
                ],
                "verbose_name": "software version",
                "verbose_name_plural": "software versions",
            },
        ),
        migrations.RemoveIndex(
            model_name="softwareversion",
            name="version_num_idx",
        ),
        migrations.AddField(
            model_name="softwareversion",
            name="version_major",
            field=models.IntegerField(
                blank=True,
                editable=False,
                help_text="Auto‑populated from version_number",
                null=True,
                verbose_name="major version",
            ),
        ),
        migrations.AddField(
            model_name="softwareversion",
            name="version_minor",
            field=models.IntegerField(
                blank=True, editable=False, null=True, verbose_name="minor version"
            ),
        ),
        migrations.AddField(
            model_name="softwareversion",
            name="version_patch",
            field=models.IntegerField(
                blank=True, editable=False, null=True, verbose_name="patch version"
            ),
        ),
        migrations.AddField(
            model_name="softwareversion",
            name="version_prerelease",
            field=models.CharField(
                blank=True, editable=False, max_length=50, verbose_name="prerelease tag"
            ),
        ),
        migrations.AlterField(
            model_name="softwaredocument",
            name="file",
            field=models.FileField(
                max_length=500,
                upload_to="software_docs/%Y/%m/%d/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["pdf", "doc", "docx", "txt", "md", "rtf"]
                    )
                ],
                verbose_name="file",
            ),
        ),
        migrations.AlterField(
            model_name="softwareimage",
            name="image",
            field=models.ImageField(
                max_length=500,
                upload_to="software_images/%Y/%m/%d/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["jpg", "jpeg", "png", "gif", "svg", "webp"]
                    )
                ],
                verbose_name="image",
            ),
        ),
        migrations.AlterField(
            model_name="softwareversion",
            name="binary_checksum",
            field=models.CharField(
                blank=True,
                editable=False,
                help_text="SHA-256 checksum of the binary",
                max_length=64,
                verbose_name="binary checksum",
            ),
        ),
        migrations.AlterField(
            model_name="softwareversion",
            name="binary_file",
            field=models.FileField(
                max_length=500,
                upload_to="software/%Y/%m/%d/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=[
                            "exe",
                            "msi",
                            "dmg",
                            "deb",
                            "rpm",
                            "zip",
                            "tar.gz",
                            "appimage",
                        ]
                    ),
                    backend.apps.products.models.SoftwareVersion.validate_file_size,
                ],
                verbose_name="binary file",
            ),
        ),
        migrations.AlterField(
            model_name="softwareversion",
            name="binary_size",
            field=models.BigIntegerField(
                default=0, editable=False, verbose_name="binary size"
            ),
        ),
        migrations.AlterField(
            model_name="softwareversion",
            name="installer_file",
            field=models.FileField(
                blank=True,
                max_length=500,
                null=True,
                upload_to="installers/%Y/%m/%d/",
                validators=[
                    backend.apps.products.models.SoftwareVersion.validate_file_size
                ],
                verbose_name="installer file",
            ),
        ),
        migrations.AlterField(
            model_name="softwareversion",
            name="signature_file",
            field=models.FileField(
                blank=True,
                max_length=500,
                null=True,
                upload_to="signatures/%Y/%m/%d/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["sig", "asc", "sign"]
                    )
                ],
                verbose_name="signature file",
            ),
        ),
        migrations.AddIndex(
            model_name="softwareversion",
            index=models.Index(
                fields=["version_major", "version_minor", "version_patch"],
                name="version_semver_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="softwaredocument",
            constraint=models.UniqueConstraint(
                fields=("software", "document_type", "version", "language"),
                name="unique_document_per_software_type_version_lang",
            ),
        ),
        migrations.AddConstraint(
            model_name="softwareimage",
            constraint=models.UniqueConstraint(
                condition=models.Q(("image_type", "LOGO")),
                fields=("software", "image_type"),
                name="unique_logo_per_software",
            ),
        ),
    ]
