# Generated by Django 4.2.28 on 2026-02-13 19:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("licenses", "0002_activationcode_expiry_reminders_sent_and_more"),
        ("products", "0002_alter_softwareversion_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SoftwareUsageEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("launch", "Launch"),
                            ("feature_x_used", "Feature X Used"),
                        ],
                        help_text="Type of usage event",
                        max_length=50,
                    ),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "activation_code",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="usage_events",
                        to="licenses.activationcode",
                    ),
                ),
                (
                    "software",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usage_events",
                        to="products.software",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="software_usage_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "software usage event",
                "verbose_name_plural": "software usage events",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["software", "created_at"],
                        name="products_so_softwar_d87d75_idx",
                    ),
                    models.Index(
                        fields=["user", "created_at"],
                        name="products_so_user_id_88ff7a_idx",
                    ),
                    models.Index(
                        fields=["event_type"], name="products_so_event_t_ccfa2b_idx"
                    ),
                    models.Index(
                        fields=["software", "event_type", "created_at"],
                        name="products_so_softwar_155d69_idx",
                    ),
                ],
            },
        ),
    ]
